server {
  listen 80;
  server_name _;

  resolver 1.1.1.1 8.8.8.8 ipv6=off;

  root /usr/share/nginx/html;
  index index.html;

  location = /storage/events {
    proxy_pass https://jsonblob.com/api/jsonBlob/019d9ff9-b1f7-7842-82b4-f09c06db506c;
    proxy_ssl_server_name on;
    proxy_ssl_name jsonblob.com;
    proxy_set_header Host jsonblob.com;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location = /storage/registrations {
    proxy_pass https://jsonblob.com/api/jsonBlob/019d9ffa-ce4b-756e-94a4-de4a31a8e47a;
    proxy_ssl_server_name on;
    proxy_ssl_name jsonblob.com;
    proxy_set_header Host jsonblob.com;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
