import { Router } from "express";
import authRoutes from "./auth.js";
import eventsRoutes from "./events.js";
import registrationsRoutes from "./registrations.js";
import helpArticlesRoutes from "./helpArticles.js";
import eventFeedbackRoutes from "./eventFeedback.js";
import userActionsRoutes from "./userActions.js";
import siteSessionsRoutes from "./siteSessions.js";
import paymentsRoutes from "./payments.js";
import sponsorsRoutes from "./sponsors.js";
import notificationsRoutes from "./notifications.js";
import adminRoutes from "./admin.js";
import publicSettingsRoutes from "./publicSettings.js";
import testimonialsRoutes from "./testimonials.js";
import formFieldsRoutes from "./formFields.js";
import contactRoutes from "./contact.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRoutes);
apiRouter.use("/events", eventsRoutes);
apiRouter.use("/registrations", registrationsRoutes);
apiRouter.use("/help-articles", helpArticlesRoutes);
apiRouter.use("/event-feedback", eventFeedbackRoutes);
apiRouter.use("/user-actions", userActionsRoutes);
apiRouter.use("/site-sessions", siteSessionsRoutes);
apiRouter.use("/payments", paymentsRoutes);
apiRouter.use("/sponsors", sponsorsRoutes);
apiRouter.use("/notifications", notificationsRoutes);
apiRouter.use("/public-settings", publicSettingsRoutes);
apiRouter.use("/testimonials", testimonialsRoutes);
apiRouter.use("/admin", adminRoutes);
apiRouter.use("/form-fields", formFieldsRoutes);
apiRouter.use("/contact", contactRoutes);
